enc:
  required: True
  type: dict
  schema:
    size:
      required: True
      type: list #Tuple(float float)
      maxlength: 2
      schema:
        type: float
    center:
      required: True
      type: list #Tuple(float float)
      maxlength: 2
      schema:
        type: float
    buffer:
      required: True
      type: integer
      min: 0
    tolerance:
      required: True
      type: float
      min: 0
    layers:
      required: True
      type: list
      allowed: ["seabed", "land", "shore"]
      minlength: 1
      maxlength: 3
      schema:
        type: float
    depths:
      required: True
      type: list
      minlength: 1
      schema:
        type: float
    files:
      required: True
      type: list
      minlength: 1
      schema:
        type: string
    new_data:
      required: True
      type: boolean
    raw_data:
      required: True
      type: boolean
    border:
      required: True
      type: boolean
    verbose:
      required: True
      type: boolean
    center_lla:
      required: False
      type: list #Tuple(float float)
      maxlength: 2
      schema:
        type: float
display:
  required: True
  type: dict
  schema:
    dpi:
      required: True
      type: integer
    anchor:
      required: True
      type: string
    resolution:
      required: True
      type: integer
    full_screen_mode:
      required: True
      type: boolean
    color_bar:
      required: True
      type: boolean
    dark_mode:
      required: True
      type: boolean
